### ISSUE TITLE
Column type JSON - IOException 

### ISSUE THREAD

**Issue by krowinski** [shyiko/mysql-binlog-connector-java#129]
Hi

Mysql 5.7

I got some problems with json column data decoding.

examples

` master.execute("INSERT INTO t1 VALUES (3, '{\"a\":true, \"a\":\"b\",  \"c\":\"d\",\"ab\":\"testtest\", \"bc\": [\"x\", \"y\"]}');");`

`
Exception in thread "main" java.io.IOException: The offset for the value in the JSON binary document is 9740, which is larger than the binary form of the JSON document (63 bytes)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseObject(JsonBinary.java:364)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:216)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:210)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168)
`

----

` master.execute("INSERT INTO t1 VALUES (3, '{\"a\":\"b\",  \"c\":\"d\",\"ab\":\"LONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONG\", \"bc\": [\"x\", \"y\"]}');");`

`
Exception in thread "main" java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
        at java.io.InputStream.read(InputStream.java:170)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:96)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:89)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseString(JsonBinary.java:629)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:252)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseObject(JsonBinary.java:398)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:216)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:210)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181)
        at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168)
`

**Comment by shyiko** [comment]
Hi @krowinski. Which version of mysql-binlog-connector-java are you using (there was a bug in 0.5.0 that could lead to something line this but it was fixed in 0.5.1)?

**Comment by krowinski** [comment]
`
On branch master
Your branch is up-to-date with 'origin/master'.
`

**Comment by shyiko** [comment]
Yeah, I haven't moved changed from 0.5.1 to master yet. Here is what is missing - https://github.com/shyiko/mysql-binlog-connector-java/commit/881e9c785ff71a9f14ea8e44d0e6a3bc4346b535.

**Comment by krowinski** [comment]
Tested on 0.5.1 same problems

**Comment by shyiko** [comment]
Confirmed. I'll look into it over the weekend (event deserialization itself isn't affected but something is wrong with JsonBinary logic). :bowing_man:

**Comment by krowinski** [comment]
I think the problem is in method readVariableInt (https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/json/JsonBinary.java#L941)
 
Did you check 5.7 json_binary lib ?

https://github.com/mysql/mysql-server/blob/5.7/sql/json_binary.cc#L234

**Comment by shyiko** [comment]
@krowinski Fixed in [0.5.2](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md#052---2016-11-19). It should became available through Maven Central within ~20 minutes or so. Thanks for the ticket!
