### ISSUE TITLE
JsonStringFormatter ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by PhantomThief** [shyiko/mysql-binlog-connector-java#145]
raw:[0, 4, 0, 102, 0, 32, 0, 5, 0, 37, 0, 9, 0, 46, 0, 11, 0, 57, 0, 17, 0, 12, 74, 0, 12, 86, 0, 4, 1, 0, 4, 1, 0, 109, 117, 115, 105, 99, 109, 117, 115, 105, 99, 78, 97, 109, 101, 104, 97, 115, 77, 117, 115, 105, 99, 84, 97, 103, 104, 97, 115, 87, 101, 98, 112, 76, 111, 119, 81, 117, 97, 108, 105, 116, 121, 11, 50, 55, 54, 56, 54, 55, 52, 52, 48, 36, 53, 15, -27, -120, -102, -27, -91, -67, -23, -127, -121, -24, -89, -127, -28, -67, -96]
java.lang.ArrayIndexOutOfBoundsException: 21018
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonStringFormatter.appendString(JsonStringFormatter.java:218)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonStringFormatter.value(JsonStringFormatter.java:111)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseString(JsonBinary.java:639)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:247)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseObject(JsonBinary.java:400)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:211)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:205)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168)

**Comment by shyiko** [comment]
Hi. Any chance you can provide the original value? Also, make sure mysql-binlog-connector-java is 0.5.2 or newer.

**Comment by PhantomThief** [comment]
the original value is 
{"music":"276867440$5","musicName":"刚好遇见你","hasMusicTag":true,"hasWebpLowQuality":true}

I dump it from my production envirorment. mysql-binlog-connector-java ver is 0.8.0.

**Comment by PhantomThief** [comment]
beside there is escape bug following.
see 
https://github.com/shyiko/mysql-binlog-connector-java/pull/146

**Comment by shyiko** [comment]
@PhantomThief 0.8.1 deployed to Maven Central (sync should take no more than 20-30 minutes). Thanks again for the PR!
