### ISSUE TITLE
BinaryLogClient should use timeout when opening socket

### ISSUE THREAD

**Issue by rhauch** [shyiko/mysql-binlog-connector-java#150]
Some Debezium users are running into situations where the binary log client attempts to open a socket but since no timeout is specified in `Socket.connect` the thread ends up waiting like this:

```
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	- locked <0x00000007529c3378> (a java.net.SocksSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.openChannel(BinaryLogClient.java:467)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:405)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$5.run(BinaryLogClient.java:632)
	at java.lang.Thread.run(Thread.java:745)
```

If this happens but the Debezium code calls `disconnect()` on the client before the socket establishes a connection, then if the socket actually does establish a connection the client will continue running and will not stop.

First, the client's `openChannel()` should use `Socket.connect(SocketAddress address, int timeout)`, and preferably the same timeout as specified when we call `connect(long timeout)` on the client.

Second, to handle the race condition mentioned above, the `connect()` method should be able to check upon successful connection whether the client should abort the connection.

**Comment by shyiko** [comment]
Hi Randall,

0.9.0 ([release note](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md#090---2017-02-07)) has just been deployed to Maven Central. This should solve the immediate problem (no socket connection timeout).

As for the race condition, `connect` & `disconnect` are guarded by the same lock (`connectLock`) and so unless I'm missing something it should not be possible to get into that situation. Do you, by any chance, have a test case (or some other way of reproducing the problem)? 

Thank you.

**Comment by rhauch** [comment]
@shyiko, I don't have a test case, but was working with a community user looking at logs and trying to figure out what was happening. They're running on a hosted environment, and the network sometimes has some very unexpected behaviors. The `connectLock` should be sufficient, especially with timeouts to prevent deadlocking. Thanks!!

**Comment by shyiko** [comment]
@rhauch Alright, I'll close the issue then. All the necessary code to prevent deadlocks is already there. Thank for the issue! :handshake:
