### ISSUE TITLE
Exception resolving JSON field with empty key("").

### ISSUE THREAD

**Issue by PhantomThief** [shyiko/mysql-binlog-connector-java#170]
`java.io.IOException: The key offset in the JSON document is 11 and is too big for the binary form of the document (11)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.readUnsignedIndex(JsonBinary.java:876)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseObject(JsonBinary.java:330)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:211)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseObject(JsonBinary.java:400)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:211)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:205)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168)`

example mysql data:
`{"bitrate": {"": 0}}`

**Comment by shyiko** [comment]
Fixed in 0.12.2 (should become available through Maven Central within ~20 minutes). Thanks for the bug report :+1:
