### ISSUE TITLE
cannot Deserializer

### ISSUE THREAD

**Issue by shipengyan** [shyiko/mysql-binlog-connector-java#175]
````
2017/06/19-19:30:23.124 DEBUG [main] com.spy.test.mysql.BinLogParserTest:41>>FORMAT_DESCRIPTION
2017/06/19-19:30:23.130 DEBUG [main] com.spy.test.mysql.BinLogParserTest:43>>FormatDescriptionEventData{binlogVersion=4, serverVersion='5.6.16-log', headerLength=19}
2017/06/19-19:30:23.132 DEBUG [main] com.spy.test.mysql.BinLogParserTest:41>>PREVIOUS_GTIDS
2017/06/19-19:30:23.133 DEBUG [main] com.spy.test.mysql.BinLogParserTest:43>>PreviousGtidSetEventData {gtidSet='4ee562ba-fa49-11e6-b2ee-6c92bf2c17fd:1-23354676'}
2017/06/19-19:30:23.135 DEBUG [main] com.spy.test.mysql.BinLogParserTest:41>>GTID
2017/06/19-19:30:23.135 DEBUG [main] com.spy.test.mysql.BinLogParserTest:43>>GtidEventData{flags=1, gtid='4ee562ba-fa49-11e6-b2ee-6c92bf2c17fd:23354677'}
2017/06/19-19:30:23.137 DEBUG [main] com.spy.test.mysql.BinLogParserTest:41>>QUERY
2017/06/19-19:30:23.137 DEBUG [main] com.spy.test.mysql.BinLogParserTest:43>>QueryEventData{threadId=705139395, executionTime=0, errorCode=0, database='llqprd', sql='BEGINB��'}
2017/06/19-19:30:23.141 DEBUG [main] com.spy.test.mysql.BinLogParserTest:41>>TABLE_MAP
2017/06/19-19:30:23.141 DEBUG [main] com.spy.test.mysql.BinLogParserTest:43>>TableMapEventData{tableId=1298, database='llqprd', table='qrtz_fired_triggers', columnTypes=15, 15, 15, 15, 15, 8, 8, 3, 15, 15, 15, 15, 15, columnMetadata=360, 285, 600, 600, 600, 0, 0, 0, 48, 600, 600, 3, 3, columnNullability={9, 10, 11, 12}}

com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1497587043000, eventType=UPDATE_ROWS, serverId=2675837255, headerLength=19, dataLength=304, nextPosition=733, flags=0}

	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:214)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:182)
	at com.github.shyiko.mysql.binlog.BinaryLogFileReader.readEvent(BinaryLogFileReader.java:82)
	at com.spy.test.mysql.BinLogParserTest.run(BinLogParserTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
	at java.io.InputStream.read(InputStream.java:170)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:96)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:89)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readString(ByteArrayInputStream.java:66)
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeVarString(AbstractRowsEventDataDeserializer.java:372)
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:178)
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:132)
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserializeRows(UpdateRowsEventDataDeserializer.java:71)
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58)
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:33)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:208)
	... 30 more


````

**Comment by shyiko** [comment]
@shipengyan see https://github.com/shyiko/mysql-binlog-connector-java/issues/158#issuecomment-290755649. I believe this should resolve your issue. Let me know if it's not the case. Thank you.
