### ISSUE TITLE
SocketException when running multiple BinaryLogClient processes

### ISSUE THREAD

**Issue by nikhilrajendra** [shyiko/mysql-binlog-connector-java#185]
I have two separate jobs which connect to the same mysql server and read the binlogs.
Both set a different servedId in the BinaryLogClient instance. When one of the program is running, the other is unable to establish a connection.
It seems like having multiple instances running is causing this issue. Any help on this is much appreciated.
```
WARNING: Failed to establish connection in 2982ms. Forcing disconnect.
2017-10-27 23:55:06.838 ERROR  - some error
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.github.shyiko.mysql.binlog.io.BufferedSocketInputStream.read(BufferedSocketInputStream.java:51)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readWithinBlockBoundaries(ByteArrayInputStream.java:202)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:184)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:46)
	at com.github.shyiko.mysql.binlog.network.protocol.PacketChannel.read(PacketChannel.java:59)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate(BinaryLogClient.java:696)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:494)
	at MainApp.main(MainApp.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.Run.invokeMain(Run.scala:89)
	at sbt.Run.run0(Run.scala:83)
	at sbt.Run.execute$1(Run.scala:61)
	at sbt.Run.$anonfun$run$4(Run.scala:73)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:252)
	at java.lang.Thread.run(Thread.java:745)
```

Thanks in advance.

**Comment by shyiko** [comment]
@nikhilrajendra see https://github.com/shyiko/mysql-binlog-connector-java/issues/121#issuecomment-252321233. tldr: each BinaryLogClient must have a different serverId.

**Comment by nikhilrajendra** [comment]
@shyiko thank you for the quick response. Each BinaryLogClient has a different serverId set and I still get the same error. 
`Both set a different servedId in the BinaryLogClient instance`

**Comment by shyiko** [comment]
@nikhilrajendra what version of the MySQL server is it?

**Comment by nikhilrajendra** [comment]
@shyiko 5.7.17-log

**Comment by shyiko** [comment]
@nikhilrajendra are you able to connect with `mysqlbinlog` client while BinaryLogClient is running?

**Comment by nikhilrajendra** [comment]
just tested it out, yes I am able to have mysqlbinlog running while one other BinaryLogClient program runs

**Comment by shyiko** [comment]
@nikhilrajendra alright. I'll try to get my hand on the same version of MySQL and check whether I can reproduce it.

**Comment by shyiko** [comment]
Unfortunately I was unable to reproduce the issue. Can you please assemble a sample project which demonstrates the issue? Thank you.

I used

> Vagrantfile

```java
Vagrant.configure("2") do |config|
    config.vm.box = 'lucid32'
    config.vm.box_url = 'http://files.vagrantup.com/lucid32.box'
    config.vm.provision :shell, :inline => %Q(
        sed -i.bak -r 's/(us.)?(archive|security).ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
        apt-get update && apt-get install -y make libaio1 curl # libaio1 required by mysql
        echo 'Downloading MySQL distribution ...'
        curl -sSLO https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.17-linux-glibc2.5-i686.tar.gz
        wget -O - https://github.com/datacharmer/mysql-sandbox/releases/download/3.2.13/MySQL-Sandbox-3.2.13.tar.gz | tar xzv
        (cd MySQL-Sandbox-3.2.13 && perl Makefile.PL && make && make install)
        su -c "make_replication_sandbox ~/mysql-5.7.17-linux-glibc2.5-i686.tar.gz \
            --remote_access='%' --how_many_slaves=1 --sandbox_base_port=33061 \
            --master_options='-c binlog_format=ROW' \
            --slave_options='-c binlog_format=ROW -c log-slave-updates=TRUE'" vagrant
        rm -f *.tar.gz
        sed -i -e "s/exit\ 0/\\/home\\/vagrant\\/sandboxes\\/rsandbox_mysql-5_7_17\\/restart_all; exit 0/g" /etc/rc.local
    )
    config.vm.network :forwarded_port, guest: 33061, host: 33061
    config.vm.network :forwarded_port, guest: 33062, host: 33062
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
end
```

and 

> Main.java

```java
class Main {
    public static void main(String[] args) throws Exception {
        for (int i = 1; i <= 3; i++) {
            final int k = i;
            final BinaryLogClient client = new BinaryLogClient("localhost", 33061, "msandbox", "msandbox");
            client.setServerId(client.getServerId() - i); // avoid clashes between BinaryLogClient instances
            client.setKeepAlive(false);
            client.registerEventListener(new TraceEventListener());
            client.registerLifecycleListener(new TraceLifecycleListener());
            client.setBinlogFilename("");
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        // Thread.sleep(k * 100);
                        client.connect();
                    } catch (IOException e) {
                        e.printStackTrace();
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }).start();
        }
    }
}
```

**Comment by nikhilrajendra** [comment]
@shyiko unfortunately when I started running my applications again today, I wasn't able to reproduce the errors again. Don't have any explanation as to why they started working again. I have been using AWS mysql rds instance to test my applications and the only thing I did was to reboot the db instance. 
Thank again for the help. If I'm able to reproduce the error, I shall update this thread, but for now you can close this.
Thanks a lot and apologize for the trouble.

**Comment by mahez89** [comment]
@shyiko , I am trying to read the binary log file of our RDS and facing the socket exception. So, I tried setting the serverId manually and restarted the application which is readin the bin log. We rebooted the RDS instance and after that first it got connected but after that again I am facing the same issue. There are two seperate application which is trying to connect read the bin log but both of them are facing the same issue.
```
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.github.shyiko.mysql.binlog.io.BufferedSocketInputStream.read(BufferedSocketInputStream.java:51)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readWithinBlockBoundaries(ByteArrayInputStream.java:202)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:184)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:46)
	at com.github.shyiko.mysql.binlog.network.protocol.PacketChannel.read(PacketChannel.java:59)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.confirmSupportOfChecksum(BinaryLogClient.java:861)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:514)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mahez89** [comment]
@shyiko , The issue resolved by setting client.setBinlogFilename(""), but it is reading the file from the beginning. So i am trying to figure out a solution to get the recent position. Thanks
