### ISSUE TITLE
Right usage to set binlog filename empty string

### ISSUE THREAD

**Issue by zzt93** [shyiko/mysql-binlog-connector-java#192]
From the java doc of lib:
```java
    /**
     *   <li>"" (empty string), which instructs server to stream events starting from the oldest known binlog.</li>
     */
    public void setBinlogFilename(String binlogFilename) {
        this.binlogFilename = binlogFilename;
    }
```
But simply set the filename as empty string not work:
```java
if ("".equals(binlogFilename)) {
  synchronized (gtidSetAccessLock) {
    if (gtidSet != null && "".equals(gtidSet.toString()) && gtidSetFallbackToPurged) {
      gtidSet = new GtidSet(fetchGtidPurged());
    }
  }
}
```
So I try to set `gtidSet` and `gtidSetFallbackToPurged` because the code in `connect`:
```
        client.setBinlogFilename("");
        client.setGtidSet("");
        client.setGtidSetFallbackToPurged(true);
```
But this still not right:
```
com.github.shyiko.mysql.binlog.network.ServerException: Client requested master to start replication from position > file size
	at com.github.zzt93.syncer.input.connect.LogLifecycleListener.onCommunicationFailure(LogLifecycleListener.java:24)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:921)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559)
	at com.github.zzt93.syncer.input.connect.MasterConnector.run(MasterConnector.java:120)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: Client requested master to start replication from position > file size
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:882)
	... 7 common frames omitted
```
So how to use it? Thank.

**Comment by shyiko** [comment]
If you want to stream events by filename/position `client.setBinlogFilename("");` should be enough (no need to setGtidSet*). 

After all,
```java
if ("".equals(binlogFilename)) {
  synchronized (gtidSetAccessLock) {
    if (gtidSet != null && "".equals(gtidSet.toString()) && gtidSetFallbackToPurged) {
      gtidSet = new GtidSet(fetchGtidPurged());
    }
  }
}
```
has no effect if gtidSet is null. If GTID is enabled - please make sure binlogPosition is not set (or equals 4).

**Comment by zzt93** [comment]
But just set the binlog filename not work for me, the following is the stack trace:

```
com.github.shyiko.mysql.binlog.network.ServerException: Could not find first log file name in binary log index file
	at com.github.zzt93.syncer.input.connect.LogLifecycleListener.onCommunicationFailure(LogLifecycleListener.java:24)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:921)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559)
	at com.github.zzt93.syncer.input.connect.MasterConnector.run(MasterConnector.java:120)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: Could not find first log file name in binary log index file
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:882)
	... 7 common frames omitted
2017-12-14 09:41:34,393 ERROR [syncer@stable@192.168.1.200] --- [116.62.146.35:3309] c.g.z.s.i.connect.LogLifecycleListener   : Communication failure
com.github.shyiko.mysql.binlog.network.ServerException: Client requested master to start replication from position > file size
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:882)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559)
	at com.github.zzt93.syncer.input.connect.MasterConnector.run(MasterConnector.java:120)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Do I need to reset binlogPosition?

**Comment by shyiko** [comment]
@zzt93 any chance you have vagrant box / docker image (or some other way) that can be used to reproduce the problem?

**Comment by zzt93** [comment]
I am afraid that I have no access to the binary of the MySQL server, any other way to detect the problem?
