### ISSUE TITLE
LifecycleListener report `onCommunicationFailure` repeatedly

### ISSUE THREAD

**Issue by zzt93** [shyiko/mysql-binlog-connector-java#218]
`"blc-" + hostname + ":" + port` thread report the following error repeatedly after a restart, and may become fine after another restart. Have any idea about what happening?

```
Communication failure
java.io.EOFException: null
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:46)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventHeaderV4Deserializer.deserialize(EventHeaderV4Deserializer.java:35)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventHeaderV4Deserializer.deserialize(EventHeaderV4Deserializer.java:27)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:179)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:890)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793)
```

**Comment by shyiko** [comment]
Make sure serverId is unique - https://github.com/shyiko/mysql-binlog-connector-java/issues/21#issuecomment-43259251.

**Comment by zzt93** [comment]
But shouldn't a same `serverId` cause `A slave with the same server_uuid/server_id as this slave has connected to the master` error?

**Comment by shyiko** [comment]
This issue has come up in the past a number of times - https://github.com/shyiko/mysql-binlog-connector-java/issues/58, https://github.com/shyiko/mysql-binlog-connector-java/issues/21, etc. Every time it was due to the serverId conflict. If my memory serves me right, MySQL was simply dropping the connection without any explanation.

**Comment by zzt93** [comment]
Fine, reasonable explanation. I will inspect `serverId` next time I met this error.
