### ISSUE TITLE
Crashes with mariadb (& maybe others) since 0.16.1

### ISSUE THREAD

**Issue by osheroff** [shyiko/mysql-binlog-connector-java#263]
Hi, guys, 
been chasing down reports in the wild of maxwell crashing since I upgraded to binlog-connection 0.17.0:  https://github.com/zendesk/maxwell/issues/1199

I got a repro, it happens reliably on an older version of mariadb/10.1.29 (although I've heard reports of this happening on mysql too).  git bisect lays the blame on 15e328e, but my general guess as to what's happening is that this server version is mis-reporting its checksum length and needs to be worked around. 

the docker image of the mysql server that repros this is "mariadb:10.1.29". 
cc @zzt93

**Comment by shyiko** [comment]
Hey Ben. 
Can you please try [0.19.0](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/CHANGELOG.md#0190---2019-02-13)? There were a few fixes related to that logic between 0.17.0 and 0.19.0.

**Comment by osheroff** [comment]
that seems to do it, thx Stanley.

**Comment by osheroff** [comment]
I spoke too soon.  The test suite is now super-red and angry under mysql 8 with: 

```
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1552598125000, eventType=TABLE_MAP, serverId=4321, headerLength=19, dataLength=63, nextPosition=13774, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:272) ~[mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:219) ~[mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:922) [mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:580) [mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:825) [mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190) ~[mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_171]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.fill(ByteArrayInputStream.java:96) ~[mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:89) ~[mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventMetadataDeserializer.readSignedness(TableMapEventMetadataDeserializer.java:96) ~[mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventMetadataDeserializer.deserialize(TableMapEventMetadataDeserializer.java:52) ~[mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:47) ~[mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:27) ~[mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:294) ~[mysql-binlog-connector-java-0.19.0.jar:0.19.0]
	... 6 more
```

LMK If there's anything you want me to debug and poke at

**Comment by shyiko** [comment]
It must be related to https://github.com/shyiko/mysql-binlog-connector-java/pull/251  (would be nice if you could capture the binlog for a fix)

**Comment by osheroff** [comment]
https://www.dropbox.com/s/doze3p47ruxhmdj/master.000001?dl=0

**Comment by osheroff** [comment]
got some time to dive into this.  The code for reading the `signedness` parts of the table-map metadata is incorrect, here's the actual server code: 

```
  /* use it to store signed flags, each numeric column take a bit. */
  StringBuffer<128> buf;
  unsigned char flag = 0;
  unsigned char mask = 0x80;

  for (unsigned int i = 0; i < m_table->s->fields; ++i) {
    if (is_numeric_field(m_table->field[i])) {
      Field_num *field = dynamic_cast<Field_num *>(m_table->field[i]);

      if (field->unsigned_flag) flag |= mask;

      mask >>= 1;

      // 8 fields are tested, store the result and clear the flag.
      if (mask == 0) {
        buf.append(flag);
        flag = 0;
        mask = 0x80;
      }
    }
  }

  // Stores the signedness flags of last few columns
  if (mask != 0x80) buf.append(flag);
```

Which only packs bits into the field for *numeric* columns.  So we'll have to decode how many numeric columns there are before reading the signedness.

**Comment by osheroff** [comment]
https://github.com/shyiko/mysql-binlog-connector-java/pull/264

**Comment by jpechane** [comment]
@shyiko We've been bitten quite bad by this in Debezium. Would it be possible to make a realease with the fix soon? Our users have alreaded tested it and confirm it fixes issues for them.
Thanks

**Comment by shyiko** [comment]
0.19.1 deployed to Maven Central (Thanks again, @osheroff :bowing_man: )

**Comment by jpechane** [comment]
@shyiko @osheroff Thanks a lot for the fix!
