### ISSUE TITLE
[azure] Protocol::AuthSwitchRequest  issue when maxwell connect mysql [solved]

### ISSUE THREAD

**Issue by plutoid** [shyiko/mysql-binlog-connector-java#271]
hi @shyiko ,

I have the similar issue when I need connect mysql on azure from maxwell (middleware https://maxwells-daemon.io/quickstart/ ).

from below debug output, the first authentication succeeded, it got the databases list,  but failed when binlog access authentication,  the maxwell use two libs(mysql-binlog-connector-java-0.19.1.jar and mysql-connector-java-5.1.47.jar), so maybe any implementation not right for Protocol::AuthSwitchRequest in mysql-binlog-connector-java-0.19.1.jar, could you have a look this too?

- https://dev.mysql.com/doc/internals/en/determining-authentication-method.html
- https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-

debug logs:
```
Using kafka version: 1.0.0
08:53:25,340 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
08:53:25,800 WARN  MaxwellMysqlStatus - Warning: binlog_row_image is set to MINIMAL.  This may not be what you want.
08:53:25,800 WARN  MaxwellMysqlStatus - See http://maxwells-daemon.io/compat for more information.
08:53:26,046 INFO  Maxwell - Maxwell v1.22.0 is booting (StdoutProducer), starting at Position[BinlogPosition[mysql-bin.00000
3:4790], lastHeartbeat=0]
08:53:26,194 DEBUG MysqlSavedSchema - looking to restore schema at target position Position[BinlogPosition[mysql-bin.000003:4
790], lastHeartbeat=0]
08:53:26,199 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[mysql-bin.000003:4790],
 lastHeartbeat=0])
08:53:26,200 DEBUG MysqlSavedSchema - Restoring full schema
08:53:26,227 DEBUG MysqlSavedSchema - Restoring database maxwell...
08:53:26,299 DEBUG MysqlSavedSchema - Restoring database mysql...
08:53:26,326 DEBUG MysqlSavedSchema - Restored all databases
08:53:26,348 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.000003:4790
08:53:26,480 INFO  TaskManager - Stopping 3 tasks
08:53:26,480 ERROR TaskManager - cause:
com.github.shyiko.mysql.binlog.network.AuthenticationException: Unexpected authentication result (-2)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate(BinaryLogClient.java:726) ~[mysql-binlog-connector-jav
a-0.19.1.jar:0.19.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:514) ~[mysql-binlog-connector-java-0.1
9.1.jar:0.19.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:825) ~[mysql-binlog-connector-java-0.19.
1.jar:0.19.1]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
08:53:26,485 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@167dac2a
08:53:26,485 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNIN
G)
08:53:26,485 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@620dedad
08:53:26,485 INFO  StoppableTaskState - com.zendesk.maxwell.bootstrap.BootstrapController requestStop() called (in state: RUN
NING)
```
Regards, Hua

_Originally posted by @plutoid in https://github.com/shyiko/mysql-binlog-connector-java/issues/253#issuecomment-484417870_

**Comment by plutoid** [comment]
issue fixed by pr https://github.com/shyiko/mysql-binlog-connector-java/pull/272
