### ISSUE TITLE
Getting EventDataDeserializationException Caused by: java.io.EOFException

### ISSUE THREAD

**Issue by upendra1024** [shyiko/mysql-binlog-connector-java#283]
Some data migration is going on mysql server.
and getting below exception. I have retry code handled through onCommunicationFailure listener, and it is working perfectly.
But I want to know why this is happening frequently? Is there something I could configuration(connection timeOut) to minimise it?

2019-06-23 02:58:45,225 INFO KafkaBinLogReader: Listener onCommunicationFailure : BinLogName - bin.000916, Position - 608745, ClientServerId - 486955897
2019-06-23 02:58:45,226 WARN KafkaBinLogReader: onCommunicationFailure due to :
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1561234482000, eventType=EXT_UPDATE_ROWS, serverId=1294418, headerLength=19, dataLength=20473, nextPosition=629320, flags=0}
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:216)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:184)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:890)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559)
        at com.zoho.mysqlbackup.producer.KafkaBinLogReader.connect(KafkaBinLogReader.java:1319)
        at com.zoho.mysqlbackup.producer.KafkaBinLogReader.readBinLog(KafkaBinLogReader.java:301)
        at com.zoho.mysqlbackup.producer.KafkaBinLogReader.run(KafkaBinLogReader.java:266)
Caused by: java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
        at java.io.InputStream.read(InputStream.java:170)
        at java.io.InputStream.skip(InputStream.java:224)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:212)

**Comment by enterwhat** [comment]
请问你解决了吗？啥原因？
