### ISSUE TITLE
Error: java.io.IOException: Unexpected packed number byte 255

### ISSUE THREAD

**Issue by DPGrev** [shyiko/mysql-binlog-connector-java#304]
Our replication of the binlog was fine but after a restart we are seeing the following error when using the binlog connector:

```
java.io.IOException: Unexpected packed number byte 255
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readPackedNumber(ByteArrayInputStream.java:162) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readPackedInteger(ByteArrayInputStream.java:131) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readLengthEncodedString(ByteArrayInputStream.java:73) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.network.protocol.ResultSetRowPacket.<init>(ResultSetRowPacket.java:35) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.readResultSet(BinaryLogClient.java:1083) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.fetchBinlogChecksum(BinaryLogClient.java:916) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:533) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) ~[mysql-binlog-connector-java-0.20.0.jar:0.20.0]
```

We think this is caused by the following piece of code, we are however unsure what causes it.

https://github.com/shyiko/mysql-binlog-connector-java/blob/d466f72f083cf6e1c17d2d481131fa2d68f8b26f/src/main/java/com/github/shyiko/mysql/binlog/io/ByteArrayInputStream.java#L149-L163

Did anybody else encounter this issue?

**Comment by DPGrev** [comment]
After some research we came to the following conclusion: https://github.com/zendesk/maxwell/issues/1374#issuecomment-553470683
