### ISSUE TITLE
EOFException trying to conect to azure mysql server with forced SSL

### ISSUE THREAD

**Issue by Kinstorm** [shyiko/mysql-binlog-connector-java#314]
We´re using the library to listen the changes that are made in the database binlog, working in local or in the azure mysql DB without forcing the ssl there is no problem. But at the time of activating the ssl, the connection with the database is cut by an error and we can not move forward. We have checked all, but still we don't know what could be the cause. We're using 0.20.1.

java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:46)
	at com.github.shyiko.mysql.binlog.network.protocol.PacketChannel.read(PacketChannel.java:59)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate(BinaryLogClient.java:722)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:515)

Best regards.

**Comment by odybour** [comment]
I am having the same issue. Any update on this?

**Comment by cubbuk** [comment]
Same here, trying to connect through debezium but we get an authentication error at the stage of reading from binlog.

**Comment by seattlecyclist** [comment]
Same here.

Here is the my stacktrace:
```
org.apache.kafka.connect.errors.ConnectException: Unable to connect to the MySQL database at host.docker.internal:3306 with user 'root': Failed to connect to MySQL on host.docker.internal:3306. Please make sure it's running.
	at io.debezium.connector.mysql.BinlogReader.doStart(BinlogReader.java:445)
	at io.debezium.connector.mysql.AbstractReader.start(AbstractReader.java:116)
	at io.debezium.connector.mysql.ChainedReader.startNextReader(ChainedReader.java:206)
	at io.debezium.connector.mysql.ChainedReader.readerCompletedPolling(ChainedReader.java:158)
	at io.debezium.connector.mysql.AbstractReader.cleanupResources(AbstractReader.java:309)
	at io.debezium.connector.mysql.AbstractReader.poll(AbstractReader.java:288)
	at io.debezium.connector.mysql.ChainedReader.poll(ChainedReader.java:146)
	at io.debezium.connector.mysql.MySqlConnectorTask.doPoll(MySqlConnectorTask.java:442)
	at io.debezium.connector.common.BaseSourceTask.poll(BaseSourceTask.java:136)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:259)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to connect to MySQL on host.docker.internal:3306. Please make sure it's running.
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:518)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:838)
	... 1 more
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:515)
	... 2 more
[2020-10-19 23:33:42,078] ERROR WorkerSourceTask{id=mothership-connector2-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
```

**Comment by willenigma** [comment]
https://github.com/osheroff/mysql-binlog-connector-java/issues/18

This link may help.
