### ISSUE TITLE
EOFException while reading binlog

### ISSUE THREAD

**Issue by syed72** [shyiko/mysql-binlog-connector-java#58]
I am getting below exception when trying to read the binlog at position given binlog at 52194840
Communication failure,Exception e: java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:182)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:46)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventHeaderV4Deserializer.deserialize(EventHeaderV4Deserializer.java:37)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventHeaderV4Deserializer.deserialize(EventHeaderV4Deserializer.java:27)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:143)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:595)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:376)
        at com.github.shyiko.mysql.binlog.BinaryLogClient$4.run(BinaryLogClient.java:516)
        at java.lang.Thread.run(Thread.java:744)

# at 52194813
#150728 20:15:14 server id 15836018  end_log_pos 52194840       Xid = 34592233
COMMIT/*!*/;
# at 52194840
#150728 20:15:20 server id 15836018  end_log_pos 52194909       Query   thread_id=2267740       exec_time=0     error_code=0
SET TIMESTAMP=1438094720/*!*/;
BEGIN
/*!*/;
# at 52194909
#150728 20:15:20 server id 15836018  end_log_pos 52195009       Query   thread_id=2267740       exec_time=0     error_code=0
SET TIMESTAMP=1438094720/*!*/;
update TimeTable set Time=1438094720
/*!*/;
# at 52195009
#150728 20:15:20 server id 15836018  end_log_pos 52195036       Xid = 34592241
COMMIT/*!*/;

**Comment by shyiko** [comment]
Hi @syed72. Try opening the same binlog with [BinaryLogFileReader](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogFileReader.java). If it works - please look at #21.

**Comment by syed72** [comment]
Problem was with same serverid, solved it, Thanks. Closing the issue
