### ISSUE TITLE
EventDataDeserializationException

### ISSUE THREAD

**Issue by syed72** [shyiko/mysql-binlog-connector-java#61]
Here are the 2 Exceptions thrown for LOAD eventtype and DECIMAL datatype not supported?

May i know why decimal is not supported? and also how can i handle LOAD event type?

Failed to deserialize data of EventHeaderV4{timestamp=33592832000, eventType=LOAD, serverId=9109502, headerLength=19, dataLength=436235757, nextPosition=391498579, flags=19224}
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:180)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:148)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:595)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:376)
        at com.github.shyiko.mysql.binlog.BinaryLogClient$4.run(BinaryLogClient.java:516)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:182)
        at java.io.InputStream.read(InputStream.java:170)
        at java.io.InputStream.skip(InputStream.java:224)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:208)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:176)
        ... 5 more

Failed to deserialize data of EventHeaderV4{timestamp=1439387551000, eventType=WRITE_ROWS, serverId=712198936, headerLength=19, dataLength=85, nextPosition=46282643, flags=0}
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:180)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:148)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:595)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:376)
        at com.github.shyiko.mysql.binlog.BinaryLogClient$4.run(BinaryLogClient.java:516)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Unsupported type DECIMAL
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:160)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:99)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserializeRows(WriteRowsEventDataDeserializer.java:64)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:56)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:32)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:174)
        ... 5 more

Most of the times binary log client gets struck at one place by throwing below error
Failed to deserialize data of EventHeaderV4{timestamp=1439386803000, eventType=UPDATE_ROWS, serverId=435234, headerLength=19, dataLength=367, nextPosition=49445536, flags=0}
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:180)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:148)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:595)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:376)
        at com.github.shyiko.mysql.binlog.BinaryLogClient$4.run(BinaryLogClient.java:516)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:182)
        at java.io.InputStream.read(InputStream.java:170)
        at java.io.InputStream.skip(InputStream.java:224)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:208)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:176)
        ... 5 more

In below exception, there is binlog name and current position:

I noticed here that, nextPosition is 27454121 and dataLength is 553, when i sum up current position and data length, is not equal to nextposition value, which leads to this exception, 

Note that, here server ids are different across replication stream.

bin.002168 27453549 : com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1439385739000, eventType=UPDATE_ROWS, serverId=435234, headerLength=19, dataLength=553, nextPosition=27454121, flags=0}
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:180)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:148)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:595)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:376)
        at com.github.shyiko.mysql.binlog.BinaryLogClient$4.run(BinaryLogClient.java:516)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:182)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:46)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:150)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:99)
        at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserializeRows(UpdateRowsEventDataDeserializer.java:71)
        at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58)

Thanks

**Comment by shyiko** [comment]
Hi. 

Please specify version of MySQL, table definition which resulted in "DECIMAL". EventDataDeserializer was not implemented for LOAD event which - you should be getting null (as event data) provided you haven't configured custom EventDeserializer.

Thank you.

**Comment by syed72** [comment]
Mysql 5.5.21 and table definition doesn't contain any decimal type. 

As u said earlier in closed issue #51 , can u provide me custom EventHeaderV4Deserializer snippet?

I'm confused how to implement that
Thank you

**Comment by shyiko** [comment]
@syed72 you don't need custom EventHeaderV4Deserializer. LOAD event data should be null unless EventDeserializer initialization is messed up.

>  EventDataDeserializer was not implemented for LOAD event which means - you should be getting null (as event data) provided you haven't configured custom EventDeserializer.

Regarding DECIMAL - please copy/paste table definition.

**Comment by syed72** [comment]
regarding DECIMAL, below is the definition of table, Here no decimal type is there in that definition

CREATE TABLE `AccountsInfo` (
  `ACCOUNTID` bigint(19) NOT NULL DEFAULT '0',
  `col1` text,
  `col2` text,
  `col3` text,
  `col4` text,
  `col5` text,
  `col6` text,
  `col7` text,
  `col8` text,
  `col9` text,
  `col10` text,
  `col11` text,
  `col12` text,
  `col13` text,
  `col14` text,
  `col15` text,
  `col16` text,
  `col17` text,
  `col18` text,
  `col19` text,
  `col20` text,
  `col21` text,
  `col22` text,
  `col23` text,
  `col24` text,
  `col25` text,
  `col26` text,
  `col27` text,
  `col28` text,
  `col29` text,
  `col30` text,
  `col31` text,
  `col32` text,
  `col33` text,
  `col34` text,
  `col35` text,
  `col36` text,
  `col37` text,
  `col38` text,
  `col39` text,
  `col40` text,
  `col41` text,
  `col42` text,
  `col43` text,
  `col44` text,
  `col45` text,
  `col46` text,
  `col47` text,
  `col48` text,
  `col49` text,
  `col50` text,
  `col51` int(10) DEFAULT NULL,
  `col52` int(10) DEFAULT NULL,
  `col53` int(10) DEFAULT NULL,
  `col54` int(10) DEFAULT NULL,
  `col55` int(10) DEFAULT NULL,
  `col56` int(10) DEFAULT NULL,
  `col57` int(10) DEFAULT NULL,
  `col58` int(10) DEFAULT NULL,
  `col59` int(10) DEFAULT NULL,
  `col60` int(10) DEFAULT NULL,
  `col61` int(10) DEFAULT NULL,
  `col62` int(10) DEFAULT NULL,
  `col63` int(10) DEFAULT NULL,
  `col64` int(10) DEFAULT NULL,
  `col65` int(10) DEFAULT NULL,
  `col66` double DEFAULT NULL,
  `col67` double DEFAULT NULL,
  `col68` double DEFAULT NULL,
  `col69` double DEFAULT NULL,
  `col70` double DEFAULT NULL,
  `col71` double DEFAULT NULL,
  `col72` double DEFAULT NULL,
  `col73` double DEFAULT NULL,
  `col74` double DEFAULT NULL,
  `col75` double DEFAULT NULL,
  `col76` double DEFAULT NULL,
  `col77` double DEFAULT NULL,
  `col78` double DEFAULT NULL,
  `col79` double DEFAULT NULL,
  `col80` double DEFAULT NULL,
  `col81` date DEFAULT NULL,
  `col82` date DEFAULT NULL,
  `col83` date DEFAULT NULL,
  `col84` date DEFAULT NULL,
  `col85` date DEFAULT NULL,
  `col86` date DEFAULT NULL,
  `col87` date DEFAULT NULL,
  `col88` date DEFAULT NULL,
  `col89` date DEFAULT NULL,
  `col90` date DEFAULT NULL,
  `col91` datetime DEFAULT NULL,
  `col92` datetime DEFAULT NULL,
  `col93` datetime DEFAULT NULL,
  `col94` datetime DEFAULT NULL,
  `col95` datetime DEFAULT NULL,
  `col96` datetime DEFAULT NULL,
  `col97` datetime DEFAULT NULL,
  `col98` datetime DEFAULT NULL,
  `col99` datetime DEFAULT NULL,
  `col100` datetime DEFAULT NULL,
  `col101` tinyint(1) DEFAULT '0',
  `col102` tinyint(1) DEFAULT '0',
  `col103` tinyint(1) DEFAULT '0',
  `col104` tinyint(1) DEFAULT '0',
  `col105` tinyint(1) DEFAULT '0',
  `col106` tinyint(1) DEFAULT '0',
  `col107` tinyint(1) DEFAULT '0',
  `col108` tinyint(1) DEFAULT '0',
  `col109` tinyint(1) DEFAULT '0',
  `col110` tinyint(1) DEFAULT '0',
  `col111` bigint(19) DEFAULT NULL,
  `col112` bigint(19) DEFAULT NULL,
  `col113` bigint(19) DEFAULT NULL,
  `col114` bigint(19) DEFAULT NULL,
  `col115` bigint(19) DEFAULT NULL,
  `col116` bigint(19) DEFAULT NULL,
  `col117` bigint(19) DEFAULT NULL,
  `col118` bigint(19) DEFAULT NULL,
  `col119` bigint(19) DEFAULT NULL,
  `col120` bigint(19) DEFAULT NULL,
  `col121` text,
  `col122` text,
  `col123` text,
  `col124` text,
  `col125` text,
  `col126` text,
  `col127` text,
  `col128` text,
  `col129` text,
  `col130` text,
  `col131` tinyint(1) DEFAULT '0',
  `col132` tinyint(1) DEFAULT '0',
  `col133` tinyint(1) DEFAULT '0',
  `col134` tinyint(1) DEFAULT '0',
  `col135` tinyint(1) DEFAULT '0',
  `col136` tinyint(1) DEFAULT '0',
  `col137` tinyint(1) DEFAULT '0',
  `col138` tinyint(1) DEFAULT '0',
  `col139` tinyint(1) DEFAULT '0',
  `col140` tinyint(1) DEFAULT '0',
  `col141` date DEFAULT NULL,
  `col142` date DEFAULT NULL,
  `col143` date DEFAULT NULL,
  `col144` date DEFAULT NULL,
  `col145` date DEFAULT NULL,
  `col146` int(10) DEFAULT NULL,
  `col147` int(10) DEFAULT NULL,
  `col148` int(10) DEFAULT NULL,
  `col149` int(10) DEFAULT NULL,
  `col150` int(10) DEFAULT NULL,
  `col01` bigint(19) DEFAULT NULL,
  `col02` bigint(19) DEFAULT NULL,
  `col03` bigint(19) DEFAULT NULL,
  `col04` bigint(19) DEFAULT NULL,
  `col05` bigint(19) DEFAULT NULL,
  PRIMARY KEY (`ACCOUNTID`)
);

**Comment by shyiko** [comment]
Just tested on 5.5.21. Works as expected. If you are sure that this is not problem on your end and is really a bug in mysql-binlog-connector-java please provide MySQL dump OR Vagrant box OR Docker image so that I could reproduce the problem. Thank you.
