### ISSUE TITLE
Failed to deserialize data

### ISSUE THREAD

**Issue by syed72** [shyiko/mysql-binlog-connector-java#62]
Hi shyiko,

com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1439907257000, eventType=WRITE_ROWS, serverId=1415717130, headerLength=19, dataLength=9098, nextPosition=3488003, flags=0} 
at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:180) 
at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:148) 
at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:595) 
at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:376) 
at com.github.shyiko.mysql.binlog.BinaryLogClient$4.run(BinaryLogClient.java:516) 
at java.lang.Thread.run(Thread.java:744) 
Caused by: java.io.EOFException 
at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:182) 
at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readInteger(ByteArrayInputStream.java:46) 
at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:150) 
at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:99) 
at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserializeRows(WriteRowsEventDataDeserializer.java:64) 
at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:56) 
at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:32) 
at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:174) 
... 5 more 

I'm getting above mentioned exceptions, I suspect, the problem may be while reading text/blob content, 

code snippet as shown below

149: case VAR_STRING:
150: int varcharLength = meta < 256 ? inputStream.readInteger(1) :       151:inputStream.readInteger(2);
152:return "'"+inputStream.readString(varcharLength)+"'";

Note, here serverid is unique across replication stream. and also read this binlog using BinLogFileReader, no issues in that too.

Please suggest me, if anything need to be done

Thanks

**Comment by shyiko** [comment]
@syed72, try reading the same section of binary log using [BinaryLogFileReader](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogFileReader.java). Let me know if it works.

**Comment by syed72** [comment]
I tried using BinaryLogFileReader. It works fine.

**Comment by shyiko** [comment]
> Increase max_allowed_packet

If BinaryLogFileReader works fine - that (most probably) means that you either have something wrong with MySQL setup or clients fighting over the server ids. At this point it looks the former. Check server's general query log for possible reasons of disconnects. In any case, EOFException should trigger client to reconnect automatically (provided keepAlive is not false).
