### ISSUE TITLE
ArrayIndexBoundofException

### ISSUE THREAD

**Issue by syed72** [shyiko/mysql-binlog-connector-java#64]
I have pulled latest(unreleased) master source and i have faced below exception:

onEventDataDeserializationException:
java.lang.ArrayIndexOutOfBoundsException: 56
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer$UnixTime.from(AbstractRowsEventDataDeserializer.java:474)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeDatetime(AbstractRowsEventDataDeserializer.java:266)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:157)
        at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:109)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserializeRows(WriteRowsEventDataDeserializer.java:65)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:55)
        at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:31)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:174)
        at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:148)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:600)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:373)
        at com.github.shyiko.mysql.binlog.BinaryLogClient$4.run(BinaryLogClient.java:522)
        at java.lang.Thread.run(Thread.java:744)

**Comment by shyiko** [comment]
Any chance you could provide me with the binary log for that event? 

Month "57" is not what I would expect to get come across. 0.2.0 treats it as 4 years 9 months whereas upcoming release considers that to be an error.

**Comment by shyiko** [comment]
Could you please specify the arguments of com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer$UnixTime.from at the time of exception? Thank you.

**Comment by shyiko** [comment]
No response for over a week. Closing.
