### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by ehabinl** [shyiko/mysql-binlog-connector-java#88]
I am trying to use this library and it works like a wizard, but after a while it raise the following exception

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:76)
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserializeRows(UpdateRowsEventDataDeserializer.java:70)
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58)
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:33)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:174)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:148)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:630)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:405)
```

**Comment by shyiko** [comment]
Hi. You gonna have to check a heap dump (you could try VisualVM or  `-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/dump.hprof` / `jmap -F -dump:format=b,file=/tmp/dump.hprof <pid>` + MAT). It might be that changes are just to big to fit memory (too low Xmx?) or that there is a leak *outside* of `mysql-binlog-connector-java`. In any case - the only way to know for sure - is to check heap dump.
