### ISSUE TITLE
EventDataSerializationException while parsing log (mysqlbinlog can read it properly)

### ISSUE THREAD

**Issue by flozano** [shyiko/mysql-binlog-connector-java#90]
We're trying to read a binlog copied from our staging database:
```java
		try (BinaryLogFileReader reader = new BinaryLogFileReader(is)) {
			for (Event event; (event = reader.readEvent()) != null;) {
				System.out.println(event);
			}
		}
```

But we are getting:
```
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1457991594000, eventType=WRITE_ROWS, serverId=1249446540, headerLength=19, dataLength=100, nextPosition=539, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:180)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:148)
	at com.github.shyiko.mysql.binlog.BinaryLogFileReader.readEvent(BinaryLogFileReader.java:82)
	at com.flozano.importer.mysql.ReadBinLogFromFile.test(ReadBinLogFromFile.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readLong(ByteArrayInputStream.java:57)
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeCell(AbstractRowsEventDataDeserializer.java:125)
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:104)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserializeRows(WriteRowsEventDataDeserializer.java:64)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:56)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:32)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:174)
	... 26 more
```
However, `mysqlbinlog` can read the file properly:
```
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 4
#160314 22:39:52 server id 305771887  end_log_pos 120 CRC32 0x6ec29014  Start: binlog v 4, server v 5.6.16-log created 160314 22:39:52
BINLOG '
qC/nVg9vtTkSdAAAAHgAAAAAAAQANS42LjE2LWxvZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAEzgNAAgAEgAEBAQEEgAAXAAEGggAAAAICAgCAAAACgoKGRkAARSQ
wm4=
'/*!*/;
# at 120
#160314 22:39:52 server id 305771887  end_log_pos 231 CRC32 0xc21850d4  Previous-GTIDs
# b5cd1624-5f30-11e4-b4e9-1051721bd241:1-4918955,
# bb421d26-5f30-11e4-b4e9-d89d672b2ef8:1-7823820
# at 231
#160314 22:39:54 server id 1249446540  end_log_pos 279 CRC32 0xb120a00b         GTID    last_committed=0        sequence_number=0
SET @@SESSION.GTID_NEXT= 'b5cd1624-5f30-11e4-b4e9-1051721bd241:4918956'/*!*/;
# at 279
#160314 22:39:54 server id 1249446540  end_log_pos 345 CRC32 0xbc372de8         Query   thread_id=84041962      exec_time=0     error_code=0
SET TIMESTAMP=1457991594/*!*/;
SET @@session.pseudo_thread_id=84041962/*!*/;
SET @@session.foreign_key_checks=1, @@session.sql_auto_is_null=0, @@session.unique_checks=1, @@session.autocommit=1/*!*/;
SET @@session.sql_mode=524288/*!*/;
SET @@session.auto_increment_increment=1, @@session.auto_increment_offset=1/*!*/;
/*!\C utf8mb4 *//*!*/;
SET @@session.character_set_client=45,@@session.collation_connection=45,@@session.collation_server=45/*!*/;
SET @@session.lc_time_names=0/*!*/;
SET @@session.collation_database=45/*!*/;
BEGIN
/*!*/;
# at 345
#160314 22:39:54 server id 1249446540  end_log_pos 420 CRC32 0xc24f95c6         Table_map: `ufe`.`token` mapped to number 15985
# at 420
#160314 22:39:54 server id 1249446540  end_log_pos 539 CRC32 0xf0800035         Write_rows: table id 15985 flags: STMT_END_F

BINLOG '
qi/nVhOMCnlKSwAAAKQBAAAAAHE+AAAAAAEAA3VmZQAFdG9rZW4ADA8ICA8PCBAQEAgPDxBYAiwB
LAEBAAEAAQBYAiwBOg/GlU/C
qi/nVheMCnlKdwAAABsCAAAAAHE+AAAAAAEADP//CP4rAGQ5emZCR05DWTJEU0ZwQ1FkbnJHSy1o
MFNoT3hTelo5MVM4ZTNJd0hnQ2vKLhJ3RwMAALIyEndTAQAACQBTWVNfQURNSU4AAAAAAAAAAAEA
ADUAgPA=
'/*!*/;
# at 539
#160314 22:39:54 server id 1249446540  end_log_pos 570 CRC32 0x17be7389         Xid = 45716015
COMMIT/*!*/;
# at 570
#160314 22:39:57 server id 1249446540  end_log_pos 618 CRC32 0x4b5e880d         GTID    last_committed=0        sequence_number=0
SET @@SESSION.GTID_NEXT= 'b5cd1624-5f30-11e4-b4e9-1051721bd241:4918957'/*!*/;
# at 618
#160314 22:39:57 server id 1249446540  end_log_pos 684 CRC32 0xfc028164         Query   thread_id=118476453     exec_time=0     error_code=0
SET TIMESTAMP=1457991597/*!*/;
BEGIN
/*!*/;
(...)
```

The first events are de-serialized properly:
```
Event{header=EventHeaderV4{timestamp=1457991592000, eventType=FORMAT_DESCRIPTION, serverId=305771887, headerLength=19, dataLength=97, nextPosition=120, flags=0}, data=FormatDescriptionEventData{binlogVersion=4, serverVersion='5.6.16-log', headerLength=19}}
Event{header=EventHeaderV4{timestamp=1457991592000, eventType=PREVIOUS_GTIDS, serverId=305771887, headerLength=19, dataLength=92, nextPosition=231, flags=0}, data=null}
Event{header=EventHeaderV4{timestamp=1457991594000, eventType=GTID, serverId=1249446540, headerLength=19, dataLength=29, nextPosition=279, flags=0}, data=GtidEventData{flags=1, gtid='b5cd1624-5f30-11e4-b4e9-1051721bd241:4918956'}}
Event{header=EventHeaderV4{timestamp=1457991594000, eventType=QUERY, serverId=1249446540, headerLength=19, dataLength=47, nextPosition=345, flags=8}, data=QueryEventData{threadId=84041962, executionTime=0, errorCode=0, database='', sql='BEGIN�-7�'}}
Event{header=EventHeaderV4{timestamp=1457991594000, eventType=TABLE_MAP, serverId=1249446540, headerLength=19, dataLength=56, nextPosition=420, flags=0}, data=TableMapEventData{tableId=15985, database='ufe', table='token', columnTypes=15, 8, 8, 15, 15, 8, 16, 16, 16, 8, 15, 15, columnMetadata=600, 0, 0, 300, 300, 0, 1, 1, 1, 0, 600, 300, columnNullability={1, 3, 4, 5, 8, 9, 10, 11}}}
```
so it seems to be the one after the table_map:

```
# at 420
#160314 22:39:54 server id 1249446540  end_log_pos 539 CRC32 0xf0800035         Write_rows: table id 15985 flags: STMT_END_F

BINLOG '
qi/nVhOMCnlKSwAAAKQBAAAAAHE+AAAAAAEAA3VmZQAFdG9rZW4ADA8ICA8PCBAQEAgPDxBYAiwB
LAEBAAEAAQBYAiwBOg/GlU/C
qi/nVheMCnlKdwAAABsCAAAAAHE+AAAAAAEADP//CP4rAGQ5emZCR05DWTJEU0ZwQ1FkbnJHSy1o
MFNoT3hTelo5MVM4ZTNJd0hnQ2vKLhJ3RwMAALIyEndTAQAACQBTWVNfQURNSU4AAAAAAAAAAAEA
ADUAgPA=
'/*!*/;
```

**Comment by flozano** [comment]
When it fails, this is the ByteArrayInputStream's state:
![screen shot 2016-03-15 at 13 22 09](https://cloud.githubusercontent.com/assets/1159291/13777525/fdf955ee-eab0-11e5-8a90-a385cc5a2922.PNG)

Line 190 of ByteArrayInputStream is:
```java
            throw new EOFException();
```

**Comment by flozano** [comment]
This is the schema of the table to which the statement refers:
```
+------------------+--------------+------+-----+---------+-------+
| Field            | Type         | Null | Key | Default | Extra |
+------------------+--------------+------+-----+---------+-------+
| f1               | varchar(200) | NO   | PRI | NULL    |       |
| f2               | bigint(20)   | YES  |     | NULL    |       |
| f3               | bigint(20)   | NO   |     | NULL    |       |
| f4               | varchar(100) | YES  | MUL | NULL    |       |
| f5               | varchar(100) | YES  |     | NULL    |       |
| f6               | bigint(20)   | YES  |     | NULL    |       |
| f7               | bit(1)       | NO   |     | NULL    |       |
| f8               | bit(1)       | NO   |     | NULL    |       |
| f9               | bit(1)       | YES  |     | NULL    |       |
| f10              | bigint(20)   | YES  |     | NULL    |       |
| f11              | varchar(200) | YES  | MUL | NULL    |       |
| f12              | varchar(100) | YES  |     | NULL    |       |
+------------------+--------------+------+-----+---------+-------+
```

**Comment by flozano** [comment]
During debugging session, in WriteRowsEventDataDeserializer.java, in line 60:
```
    private List<Serializable[]> deserializeRows(long tableId, BitSet includedColumns, ByteArrayInputStream inputStream)
            throws IOException {
        List<Serializable[]> result = new LinkedList<Serializable[]>();
        while (inputStream.available() > 0) {
            result.add(deserializeRow(tableId, includedColumns, inputStream));
        }
        return result;
    }
```
during the first iteration of the while() loop, the row (the only one in this event, I think) seems to be properly read and de-serialized.

However, after the first iteration, `blockLength` inside `ByteArrayInputStream` should have been 0 I assume - but it's 4, so it keeps trying to read and fails.

**Comment by flozano** [comment]
Versions tested:
 - 0.3.1
 - 0.3.0
 - 0.2.4
same result.

**Comment by flozano** [comment]
Tried with other random binlog (from MySQL 5.6 too) and the same problem happens in the exact same moment (the first 'write rows' event), with blockLength being also 4 instead of 0.

**Comment by shyiko** [comment]
Hi.

Yeah, checksum (which according to mysqlbinlog output is CRC32) is not automatically resolved by EventDeserializer in case of BinaryLogFileReader (coming in 1.0.0). Until then, it needs to be specified like so (updated your original example):

```java
EventDeserializer ed = new EventDeserializer();
ed.setChecksumType(ChecksumType.CRC32);
try (BinaryLogFileReader reader = new BinaryLogFileReader(is, ed)) {
    for (Event event; (event = reader.readEvent()) != null;) {
        System.out.println(event);
    }
}
```

**Comment by flozano** [comment]
Thank you, this is relieving :+1: 

Do you know how can I check which ChecksumType corresponds to each server? is it version-bound? configuration-bound?

**Comment by shyiko** [comment]
[CRC32 (the only other option is NONE)](http://dev.mysql.com/doc/refman/5.7/en/replication-options-binary-log.html#option_mysqld_binlog-checksum) was introduced in 5.6.2 (I think) and became default in MySQL 5.6.6. You can check active `binlog-checksum` in the same way [BinaryLogClient does](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L628).

**Comment by flozano** [comment]
Thanks a lot. I will close the issue then :+1:

**Comment by shyiko** [comment]
No problem :beers:
