### ISSUE TITLE
Cannot delete or update a parent row: a foreign key constraint fails

### ISSUE THREAD

**Issue by wanghaisheng** [shyiko/mysql-binlog-connector-java#93]
i have taken those steps to backup existing mysql database and start binlog feature
```
(1)
flush tables with read lock;
show master status;
RESET MASTER;
(2)backup database medicalrecord
(3)
unlock tables;
```

then  start a binaryLogClient and  start consume from the start 
```
            client = new BinaryLogClient(hostname, port, username, password);
            client.setBinlogFilename("");
            client.registerEventListener(new DateEventListener());

```
but there is a weired error 
```
INFO: Connected to 1xxx.xxx.xxx.xxx:3306 at /4 (sid:65535, cid:1564)
java.sql.SQLException: Cannot delete or update a parent row: a foreign key constraint fails (`medicalrecord1`.`medicalanalydata`, CONSTRAINT `FK_Reference_19` FOREIGN KEY (`MRIID`) REFERENCES `medicalrecordinfo` (`ID`)) Query: replace into medicalrecordinfo(`ID`,`ReportID`,`HspsPatientID`,`HospitalName`,`HospitalCode`,`DepartmentName`,`PatientName`,`Age`,`Sex`,`BarCode`,`CheckID`,`CheckPart`,`CheckTime`,`ReportPath`,`Mobile`,`PrintStatus`,`UploadType`,`IsValid`,`CreateTime`,`ReportStatus`,`report_type`,`id_card`,`report_qr_url`) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) Parameters: [[1503894, 4805378611822254163, 0, aaaaaaaaaaa, PSA1508998303, bbbbb, cccccc, 0, 1, 6031100776, 6031100776-2, 6031100776-2, Fri Mar 11 00:00:00 CST 2016, 2016-03-11\[6031100776][6031100776-2][UnAnaly][2016-03-11 19-22-29.315], , 0, 0, 1, 2016-03-11 19:44:44.0, 0, 0, , ]]
	at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:392)
	at org.apache.commons.dbutils.QueryRunner.insertBatch(QueryRunner.java:701)
	at org.apache.commons.dbutils.QueryRunner.insertBatch(QueryRunner.java:652)
	at com.senge.v3.bin.MyWriteRows.execute(MyWriteRows.java:61)
	at com.senge.v3.bin.MySqlBinRecives.executeEvents(MySqlBinRecives.java:115)
	at com.senge.v3.bin.MySqlBinRecives.access$000(MySqlBinRecives.java:19)
	at com.senge.v3.bin.MySqlBinRecives$DateEventListener.onEvent(MySqlBinRecives.java:67)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:753)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:617)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:380)
	at com.senge.v3.bin.MySqlBinRecives.<init>(MySqlBinRecives.java:53)
	at com.senge.v3.MysqlSync.main(MysqlSync.java:48)
```

**Comment by shyiko** [comment]
@wanghaisheng I suggest you [log events](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/test/java/com/github/shyiko/mysql/binlog/TraceEventListener.java) to locate where the conflict is coming from. This definitely doesn't have anything to do with mysql-binlog-connector-java itself. Feel feel to reopen the issue if you think otherwise. Good luck!
